[package]
name = "apple-health-export-parser-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
indicatif = "0.17.11"
quick-xml = "0.37.5"
serde = { version =  "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
zip = "3.0.0"
